# Generated by Django 4.2.13 on 2024-07-11 00:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_student_current_semester'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterField(
            model_name='student',
            name='gpa_history',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid-gpahistory', message="Enter a list of gpa's per semester separated by symbol '/'. Example: 3.40/2/2.5/1.95", regex='^(4\\.00|[0-3](\\.\\d{1,2})?)(\\/(4\\.00|[0-3](\\.\\d{1,2})?))*$')]),
        ),
    ]
